#!/bin/sh
### BEGIN INIT INFO
# Provides:          fsdeploy
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: fsdeploy service
### END INIT INFO

DESC="fsdeploy service"
DAEMON=/usr/bin/fsdeploy
PIDFILE=/var/run/fsdeploy.pid
SCRIPTNAME=/etc/init.d/fsdeploy

[ -x "$DAEMON" ] || exit 0

. /lib/lsb/init-functions

case "$1" in
    start)
        log_daemon_msg "Starting $DESC" "fsdeploy"
        start-stop-daemon --start --quiet --background --make-pidfile \
            --pidfile $PIDFILE --exec $DAEMON -- service
        log_end_msg $?
        ;;
    stop)
        log_daemon_msg "Stopping $DESC" "fsdeploy"
        start-stop-daemon --stop --quiet --pidfile $PIDFILE
        log_end_msg $?
        ;;
    restart|force-reload)
        $0 stop
        sleep 1
        $0 start
        ;;
    status)
        status_of_proc -p $PIDFILE $DAEMON "fsdeploy" && exit 0 || exit $?
        ;;
    *)
        echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload|status}"
        exit 3
        ;;
esac

exit 0
